
package Login;

import connection.connectsql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import MainFrom.Main;

public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    Connection con = connectsql.getConnection();
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundlogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtlogin_username = new javax.swing.JTextField();
        btnlogin_signin = new javax.swing.JButton();
        passwordlable = new javax.swing.JLabel();
        usernamelable = new javax.swing.JLabel();
        txtlogin_password = new javax.swing.JPasswordField();
        faillable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1369, 768));

        backgroundlogin.setBackground(new java.awt.Color(204, 255, 204));
        backgroundlogin.setForeground(new java.awt.Color(204, 0, 51));
        backgroundlogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlogin_username.setText("username");
        txtlogin_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlogin_usernameKeyReleased(evt);
            }
        });
        jPanel2.add(txtlogin_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 270, 40));

        btnlogin_signin.setText("Sign In");
        btnlogin_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogin_signinMouseClicked(evt);
            }
        });
        jPanel2.add(btnlogin_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 190, 40));
        jPanel2.add(passwordlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 270, 10));
        jPanel2.add(usernamelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 270, 10));

        txtlogin_password.setText("password");
        txtlogin_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlogin_passwordKeyReleased(evt);
            }
        });
        jPanel2.add(txtlogin_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 270, 40));
        jPanel2.add(faillable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 110));

        backgroundlogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 350, 470));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/backgroundlogo.jpg"))); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(1368, 768));
        jLabel4.setPreferredSize(new java.awt.Dimension(1368, 768));
        backgroundlogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1368, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundlogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogin_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogin_signinMouseClicked
        try{
            String sql = "Select * from tbstaff where usernamelogin=? and password = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtlogin_username.getText().trim());
            String user = txtlogin_username.getText().trim().toString();
            //pst.setString(2, password.getText().trim());
            pst.setString(2,String.valueOf(txtlogin_password.getPassword()));
            
            if(txtlogin_username.getText().trim().isEmpty() && String.valueOf(txtlogin_password.getPassword()).trim().isEmpty()){
                usernamelable.setText("Username is required.");
                passwordlable.setText("Password is required.");
                txtlogin_username.requestFocus();
            }
            else if (txtlogin_username.getText().trim().isEmpty()){
                usernamelable.setText("Username is required.");
                txtlogin_username.requestFocus();
            }
            else if (String.valueOf(txtlogin_password.getPassword()).trim().isEmpty()){
                passwordlable.setText("Password is required.");
                txtlogin_password.requestFocus();
            }
            else{
                ResultSet rs = pst.executeQuery();
                if(rs.next()){      
                    
                    Main ma = new Main();
                    ma.setVisible(true);
                    this.setVisible(false);
                    
                    //sucessfullylable.setText("Sign in sucessfully.");
                    
                }
                else{
                    faillable.setText("Sign in failed.");
                    txtlogin_username.setText("");
                    txtlogin_password.setText("");
                    txtlogin_username.requestFocus();
                }
            }
//            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnlogin_signinMouseClicked

    private void txtlogin_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlogin_usernameKeyReleased
        usernamelable.setText("");
    }//GEN-LAST:event_txtlogin_usernameKeyReleased

    private void txtlogin_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlogin_passwordKeyReleased
        passwordlable.setText("");
    }//GEN-LAST:event_txtlogin_passwordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundlogin;
    private javax.swing.JButton btnlogin_signin;
    private javax.swing.JLabel faillable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passwordlable;
    private javax.swing.JPasswordField txtlogin_password;
    private javax.swing.JTextField txtlogin_username;
    private javax.swing.JLabel usernamelable;
    // End of variables declaration//GEN-END:variables
}
